project:
  type: website

website:
  title: "ISSS608-VAA-Project"
  navbar:
    left: 
      - text: "Project Proposal"
        menu: 
          - text: "Project Proposal"
            href: "Project/Proposal.html"
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: prettydoc
    css: styles.css
    toc: true

editor: visual

